main: net.shortninja.staffplus.core.StaffPlusPlus
name: e4Staff
version: ${project.version}
description: El mejor plugin de moderación para tu servidor.
author: e4vizz,e4Studio
softdepend: [PacketListenerApi, PlaceholderAPI, LuckPerms, Vault, GroupManager, AuthMe, DiscordSRV]

api-version: 1.13
